apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-08-15T20:18:26Z"
  generation: 1
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: default
  resourceVersion: "13472"
  uid: eb871914-1167-42e6-94e1-75bb87701308
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: {{ .Values.imageName }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.appName }}
        ports:
          - containerPort: 8080
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
