apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.sourcePort }}
      targetPort: 8080
  type: LoadBalancer
